# Generated by Django 3.2.6 on 2021-08-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story',
            field=models.CharField(max_length=210000),
        ),
    ]
